name: .NET CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: |
          dotnet publish "src\PinArchiverBot\PinArchiverBot.csproj" -p:PublishSingleFile=true --self-contained -c Release --os win -o win
          dotnet publish "src\PinArchiverBot\PinArchiverBot.csproj" -p:PublishSingleFile=true --self-contained -c Release --os linux -o linux
          dotnet publish "src\PinArchiverBot\PinArchiverBot.csproj" -p:PublishSingleFile=true --self-contained -c Release --os osx -o osx
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win
          path: win
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: linux
      - name: Upload OSX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: osx
          path: osx
      - name: Zip artifacts
        run: |
          Compress-Archive "win\*" -DestinationPath "win.zip" -CompressionLevel Optimal
          Compress-Archive "linux\*" -DestinationPath "linux.zip" -CompressionLevel Optimal
          Compress-Archive "osx\*" -DestinationPath "osx.zip" -CompressionLevel Optimal
      # Create a new release: create a tag, then 'git push origin <tagname>', wait for it to build
      - name: Create a new GitHub release if a new tag is pushed
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: |
            win.zip
            linux.zip
            osx.zip
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
